@startuml
left to right direction
skinparam packageStyle rectangle

actor "Secretaria" as S
actor "Rector" as R

package "Módulo Secretaría Académica" {
  usecase "HU-S01: Matricular estudiantes" as S01
  usecase "HU-S02: Gestionar retiro de estudiantes" as S02
  usecase "HU-S03: Generar certificados académicos" as S03
  usecase "HU-S04: Registrar retiro en SIMAT" as S04
  usecase "HU-S05: Adjuntar historial psicológico en retiro" as S05
}

S --> S01
S --> S02
S --> S03
S --> S04
S --> S05
R --> S02

S02 ..> S05 : <<include>>
S02 ..> S04 : <<include>>
S02 ..> R : <<extend>>
@enduml